// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Inventory.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Inventory.Models
{
    public partial class AmerichickenContext
    {
        private IAmerichickenContextProcedures _procedures;

        public virtual IAmerichickenContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AmerichickenContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAmerichickenContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class AmerichickenContextProcedures : IAmerichickenContextProcedures
    {
        private readonly AmerichickenContext _context;

        public AmerichickenContextProcedures(AmerichickenContext context)
        {
            _context = context;
        }
    }
}
