// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models;

public partial class bil_buy
{
    public Guid PK_bil_buy { get; set; }

    public string name { get; set; }

    public string bbuycode { get; set; }

    public string reg_name { get; set; }

    public string street { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip { get; set; }

    public string zip4 { get; set; }

    public string internat { get; set; }

    public string street2 { get; set; }

    public string istreet { get; set; }

    public string istreet2 { get; set; }

    public string icity { get; set; }

    public string country { get; set; }

    public string int_zip { get; set; }

    public string iline1 { get; set; }

    public string iline2 { get; set; }

    public string iline3 { get; set; }

    public decimal? cred_lim { get; set; }

    public decimal? term_days { get; set; }

    public string letter_c { get; set; }

    public DateTime? beg_date { get; set; }

    public DateTime? end_date { get; set; }

    public decimal? let_crd { get; set; }

    public string guaran { get; set; }

    public string note { get; set; }

    public string note2 { get; set; }

    public string phone { get; set; }

    public string fax { get; set; }

    public DateTime? fst_sale { get; set; }

    public decimal? cus_bal { get; set; }

    public decimal? bal_calc { get; set; }

    public string no_shrtrpt { get; set; }

    public DateTime? date_rvwd { get; set; }

    public DateTime? date_fin { get; set; }

    public string fin_prov { get; set; }

    public string cust_sw { get; set; }

    public string po_warn { get; set; }

    public decimal? high_bal { get; set; }

    public string led_code { get; set; }

    public decimal? ships { get; set; }

    public decimal? nbr_days { get; set; }

    public decimal? ships_25 { get; set; }

    public decimal? days_25 { get; set; }

    public decimal? ships_180 { get; set; }

    public decimal? days_180 { get; set; }

    public string active { get; set; }

    public string cred_bal { get; set; }

    public decimal? ships_ex { get; set; }

    public decimal? days_ex { get; set; }

    public string cred_rqst { get; set; }

    public DateTime? date_rqst { get; set; }

    public string po_attn { get; set; }

    public string credit_ap { get; set; }

    public DateTime? credap_dt { get; set; }

    public string db_rpt { get; set; }

    public DateTime? db_dt { get; set; }

    public string region { get; set; }

    public decimal? s1_lim { get; set; }

    public string s1_code { get; set; }

    public decimal? s1_bal { get; set; }

    public decimal? s2_lim { get; set; }

    public string s2_code { get; set; }

    public decimal? s2_bal { get; set; }

    public decimal? s3_lim { get; set; }

    public string s3_code { get; set; }

    public decimal? s3_bal { get; set; }

    public decimal? workships { get; set; }

    public decimal? workdays { get; set; }

    public string used { get; set; }

    public decimal? cus_bal15 { get; set; }

    public string fed_cust { get; set; }

    public string incen_cd { get; set; }

    public string no_incen { get; set; }

    public decimal? extension { get; set; }
}