// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models;

public partial class buyer
{
    public Guid PK_buyer { get; set; }

    public string name { get; set; }

    public string buy_code { get; set; }

    public string street { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip { get; set; }

    public string zip4 { get; set; }

    public string internat { get; set; }

    public string street2 { get; set; }

    public string country { get; set; }

    public string int_zip { get; set; }

    public string note { get; set; }

    public string phone { get; set; }

    public string fax { get; set; }

    public string bbuycode { get; set; }

    public decimal? cus_bal { get; set; }

    public decimal? ships_180 { get; set; }

    public decimal? ships_60 { get; set; }

    public decimal? ships_ex { get; set; }

    public decimal? days_180 { get; set; }

    public decimal? days_60 { get; set; }

    public decimal? days_ex { get; set; }

    public string used { get; set; }

    public string grp_code { get; set; }

    public string grp_desc { get; set; }

    public string mon_recv { get; set; }

    public string tue_recv { get; set; }

    public string wed_recv { get; set; }

    public string thu_recv { get; set; }

    public string fri_recv { get; set; }

    public string sat_recv { get; set; }

    public string sun_recv { get; set; }

    public string cont_name { get; set; }

    public string cont_nam2 { get; set; }

    public string cont_ph { get; set; }

    public string cont_fax { get; set; }

    public string frt_ph { get; set; }

    public string del_ph { get; set; }

    public string del_mail { get; set; }

    public string del_time { get; set; }
}