// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models;

public partial class freight
{
    public Guid PK_freight { get; set; }

    public string NAME { get; set; }

    public string FRT_CODE { get; set; }

    public string STREET { get; set; }

    public string CITY { get; set; }

    public string STATE { get; set; }

    public string ZIP { get; set; }

    public string ZIP4 { get; set; }

    public string PHONE { get; set; }

    public string FRT_CONT { get; set; }

    public string PAY_NAME { get; set; }

    public string PAY_STREET { get; set; }

    public string PAY_CITY { get; set; }

    public string PAY_ZIP { get; set; }

    public string PAY_ZIP4 { get; set; }

    public string PAY_PHONE { get; set; }

    public string FAX_PHONE { get; set; }

    public string PAY_FPHONE { get; set; }

    public string ACTIVE { get; set; }

    public string NOTE { get; set; }

    public string INS_CO1 { get; set; }

    public string INS_CO2 { get; set; }

    public string INS_CO3 { get; set; }

    public string INS_CO4 { get; set; }

    public string INS_TP1 { get; set; }

    public string INS_TP2 { get; set; }

    public string INS_TP3 { get; set; }

    public string INS_TP4 { get; set; }

    public string INS_TP5 { get; set; }

    public string POLICY1 { get; set; }

    public string POLICY2 { get; set; }

    public string POLICY3 { get; set; }

    public string POLICY4 { get; set; }

    public string POLICY5 { get; set; }

    public string INS1_TP1 { get; set; }

    public string INS1_TP2 { get; set; }

    public string INS1_TP3 { get; set; }

    public string INS1_TP4 { get; set; }

    public string INS2_TP1 { get; set; }

    public string INS2_TP2 { get; set; }

    public string INS2_TP3 { get; set; }

    public string INS2_TP4 { get; set; }

    public decimal? AUTO_COV { get; set; }

    public DateTime? AUTO_BEG { get; set; }

    public DateTime? AUTO_END { get; set; }

    public DateTime? AUTO_LET { get; set; }

    public decimal? AUTO_COV1 { get; set; }

    public decimal? AUTO_COV2 { get; set; }

    public decimal? AUTO_COV3 { get; set; }

    public decimal? AUTO_COV4 { get; set; }

    public decimal? CARGO_COV { get; set; }

    public DateTime? CARGO_BEG { get; set; }

    public DateTime? CARGO_END { get; set; }

    public DateTime? CARGO_LET { get; set; }

    public decimal? CARG_COV1 { get; set; }

    public decimal? CARG_COV2 { get; set; }

    public decimal? CARG_COV3 { get; set; }

    public decimal? CARG_COV4 { get; set; }

    public decimal? REFER_COV { get; set; }

    public DateTime? REFER_BEG { get; set; }

    public DateTime? REFER_END { get; set; }

    public DateTime? REFER_LET { get; set; }

    public DateTime? GEN_BEG { get; set; }

    public DateTime? GEN_END { get; set; }

    public DateTime? GEN_LET { get; set; }

    public decimal? GEN_COV1 { get; set; }

    public decimal? GEN_COV2 { get; set; }

    public decimal? GEN_COV3 { get; set; }

    public decimal? GEN_COV4 { get; set; }

    public decimal? GEN_COV5 { get; set; }

    public decimal? GEN_COV6 { get; set; }

    public decimal? WORK_COV { get; set; }

    public DateTime? WORK_BEG { get; set; }

    public DateTime? WORK_END { get; set; }

    public DateTime? WORK_LET { get; set; }

    public decimal? WORK_COV1 { get; set; }

    public decimal? WORK_COV2 { get; set; }

    public decimal? WORK_COV3 { get; set; }

    public DateTime? PHY_BEG { get; set; }

    public DateTime? PHY_END { get; set; }

    public decimal? PHY_COV1 { get; set; }

    public decimal? PHY_COV2 { get; set; }

    public decimal? CANCEL { get; set; }

    public string USED { get; set; }

    public string REPORT { get; set; }

    public string PAY_STATE { get; set; }
}