// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models;

public partial class po_head
{
    public Guid PK_po_head { get; set; }

    public string salesman { get; set; }

    public string po_nbr { get; set; }

    public string po_suffix { get; set; }

    public string sup_code { get; set; }

    public string rsupcode { get; set; }

    public string buy_code { get; set; }

    public string bbuycode { get; set; }

    public DateTime? del_reqd { get; set; }

    public DateTime? ord_date { get; set; }

    public string buyer_po { get; set; }

    public DateTime? ship_date { get; set; }

    public decimal? tot_lbs { get; set; }

    public decimal? tot_purch { get; set; }

    public decimal? bill_adj { get; set; }

    public decimal? tot_sell { get; set; }

    public decimal? tot_net { get; set; }

    public decimal? gross { get; set; }

    public string frt_rec { get; set; }

    public string frt_code1 { get; set; }

    public decimal? frt_amt1 { get; set; }

    public decimal? frt1_adj1 { get; set; }

    public string frt1_rs1 { get; set; }

    public string frt1_rs2 { get; set; }

    public string ref_po1 { get; set; }

    public string ref_po2 { get; set; }

    public string ref_po3 { get; set; }

    public string ref_po4 { get; set; }

    public string ref_po5 { get; set; }

    public string ref_po6 { get; set; }

    public decimal? frt_pall { get; set; }

    public string frt2_flg { get; set; }

    public string frt3_flg { get; set; }

    public string com_code { get; set; }

    public decimal? comm_cent { get; set; }

    public decimal? comm_amt { get; set; }

    public decimal? comm_adj { get; set; }

    public decimal? comm_ent { get; set; }

    public string com_code2 { get; set; }

    public decimal? comm_amt2 { get; set; }

    public decimal? comm_ent2 { get; set; }

    public decimal? comm_cen2 { get; set; }

    public string com_code3 { get; set; }

    public decimal? comm_amt3 { get; set; }

    public decimal? comm_ent3 { get; set; }

    public decimal? comm_cen3 { get; set; }

    public decimal? sale_comm { get; set; }

    public decimal? sale_cent { get; set; }

    public decimal? sale_ent { get; set; }

    public string zero_comm { get; set; }

    public decimal? sale2_amt { get; set; }

    public decimal? sale2_ent { get; set; }

    public decimal? sale2_cen { get; set; }

    public decimal? sale2_net { get; set; }

    public string sal_code2 { get; set; }

    public decimal? sale3_amt { get; set; }

    public decimal? sale3_ent { get; set; }

    public decimal? sale3_cen { get; set; }

    public decimal? sale3_net { get; set; }

    public string sal_code3 { get; set; }

    public string inv_flg { get; set; }

    public string inv_nbr { get; set; }

    public DateTime? inv_date { get; set; }

    public string sup_pd { get; set; }

    public string buyer_pd { get; set; }

    public string mid_pd { get; set; }

    public string com_pd { get; set; }

    public string frt_pd { get; set; }

    public decimal? tot_short { get; set; }

    public string short_flg { get; set; }

    public string shortflg2 { get; set; }

    public string brok_name { get; set; }

    public string pu_lock { get; set; }

    public string sup_reas1 { get; set; }

    public decimal? sup_amt1 { get; set; }

    public string sup_reas2 { get; set; }

    public decimal? sup_amt2 { get; set; }

    public decimal? sup_pall { get; set; }

    public string cus_reas1 { get; set; }

    public decimal? cus_amt1 { get; set; }

    public string cus_prt1 { get; set; }

    public string cus_reas2 { get; set; }

    public decimal? cus_amt2 { get; set; }

    public string cus_prt2 { get; set; }

    public decimal? cus_pall { get; set; }

    public string brokerage { get; set; }

    public string posted { get; set; }

    public string paid_flg { get; set; }

    public string sup_rec { get; set; }

    public decimal? writeoff { get; set; }

    public decimal? over_pd { get; set; }

    public string misc_flg { get; set; }

    public decimal? sw_lbs { get; set; }

    public decimal? sw_purch { get; set; }

    public decimal? sw_sell { get; set; }

    public string notes_flg { get; set; }

    public string main_ship { get; set; }

    public string ship_nbr { get; set; }

    public string ship_suff { get; set; }

    public string check1 { get; set; }

    public string check2 { get; set; }

    public decimal? cus_prom { get; set; }

    public decimal? brk_prom { get; set; }

    public decimal? usr_prom { get; set; }

    public decimal? case_8910 { get; set; }

    public DateTime? po_dtadd { get; set; }
}