// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models;

public partial class rem_sup
{
    public Guid PK_rem_sup { get; set; }

    public string name { get; set; }

    public string rsupcode { get; set; }

    public string street { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip { get; set; }

    public string zip4 { get; set; }

    public string pay_zip4 { get; set; }

    public decimal? cred_lim { get; set; }

    public DateTime? beg_date { get; set; }

    public DateTime? end_date { get; set; }

    public decimal? let_crd { get; set; }

    public string guaran { get; set; }

    public string note { get; set; }

    public string area_code { get; set; }

    public string phone { get; set; }

    public string fax { get; set; }

    public decimal? net_days { get; set; }

    public string led_code { get; set; }

    public string active { get; set; }

    public string temp { get; set; }

    public string used { get; set; }

    public string ins_co1 { get; set; }

    public string ins_co2 { get; set; }

    public string ins_co3 { get; set; }

    public string ins_co4 { get; set; }

    public string ins_co5 { get; set; }

    public string ins_tp1 { get; set; }

    public string ins_tp2 { get; set; }

    public string ins_tp3 { get; set; }

    public string ins_tp4 { get; set; }

    public string ins_tp5 { get; set; }

    public string policy1 { get; set; }

    public string policy2 { get; set; }

    public string policy4 { get; set; }

    public string policy5 { get; set; }

    public string ins1_tp1 { get; set; }

    public string ins1_tp2 { get; set; }

    public string ins1_tp3 { get; set; }

    public string ins1_tp4 { get; set; }

    public string ins2_tp1 { get; set; }

    public string ins2_tp2 { get; set; }

    public string ins2_tp3 { get; set; }

    public string ins2_tp4 { get; set; }

    public decimal? auto_cov { get; set; }

    public DateTime? auto_beg { get; set; }

    public DateTime? auto_end { get; set; }

    public DateTime? auto_let { get; set; }

    public decimal? auto_cov1 { get; set; }

    public decimal? auto_cov2 { get; set; }

    public decimal? auto_cov3 { get; set; }

    public decimal? auto_cov4 { get; set; }

    public decimal? exces_cov { get; set; }

    public DateTime? exces_beg { get; set; }

    public DateTime? exces_end { get; set; }

    public DateTime? exces_let { get; set; }

    public decimal? exce_cov1 { get; set; }

    public decimal? exce_cov2 { get; set; }

    public decimal? refer_cov { get; set; }

    public DateTime? refer_beg { get; set; }

    public DateTime? refer_end { get; set; }

    public DateTime? refer_let { get; set; }

    public DateTime? gen_beg { get; set; }

    public DateTime? gen_end { get; set; }

    public DateTime? gen_let { get; set; }

    public decimal? gen_cov1 { get; set; }

    public decimal? gen_cov2 { get; set; }

    public decimal? gen_cov3 { get; set; }

    public decimal? gen_cov4 { get; set; }

    public decimal? gen_cov5 { get; set; }

    public decimal? gen_cov6 { get; set; }

    public decimal? work_cov { get; set; }

    public DateTime? work_beg { get; set; }

    public DateTime? work_end { get; set; }

    public DateTime? work_let { get; set; }

    public decimal? work_cov1 { get; set; }

    public decimal? work_cov2 { get; set; }

    public decimal? work_cov3 { get; set; }

    public DateTime? recal_beg { get; set; }

    public DateTime? recal_end { get; set; }

    public DateTime? recal_let { get; set; }

    public decimal? reca_cov1 { get; set; }

    public decimal? cancel { get; set; }

    public string indem_flg { get; set; }

    public DateTime? indem_dt { get; set; }

    public string policy3 { get; set; }
}