// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models;

public partial class salesman
{
    public Guid PK_salesman { get; set; }

    public string name { get; set; }

    public string sale_code { get; set; }

    public string street { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip { get; set; }

    public string zip4 { get; set; }

    public DateTime? eff_dt1 { get; set; }

    public decimal? sale_perc { get; set; }

    public DateTime? eff_dt2 { get; set; }

    public decimal? sale_per2 { get; set; }

    public DateTime? eff_dt3 { get; set; }

    public decimal? sale_per3 { get; set; }

    public string sale_ssn { get; set; }

    public string fed_taxid { get; set; }

    public string res_ded { get; set; }

    public string res_paid { get; set; }

    public string rpt_prt { get; set; }

    public decimal? reserve { get; set; }

    public decimal? interest { get; set; }

    public decimal? withdraw { get; set; }

    public string office_cd { get; set; }

    public string active { get; set; }

    public string aprv_com { get; set; }
}