// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models;

public partial class supplier
{
    public Guid PK_supplier { get; set; }

    public string name { get; set; }

    public string sup_code { get; set; }

    public string street { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip { get; set; }

    public string zip4 { get; set; }

    public string note { get; set; }

    public string area_code { get; set; }

    public string phone { get; set; }

    public string fax { get; set; }

    public string cont_name { get; set; }

    public string cont_phone { get; set; }

    public string cont_fax { get; set; }

    public string rsupcode { get; set; }

    public string freight_phone { get; set; }

    public string fright_email { get; set; }

    public string used { get; set; }

    public string pu_code { get; set; }
}